---
development:
  cloud_name: maybenaut
  api_key: '635635438388839'
  api_secret: Fn0TFBjD6zb2A0M3p9GQFQfM_7Y
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: maybenaut
  api_key: '635635438388839'
  api_secret: Fn0TFBjD6zb2A0M3p9GQFQfM_7Y
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: maybenaut
  api_key: '635635438388839'
  api_secret: Fn0TFBjD6zb2A0M3p9GQFQfM_7Y
  enhance_image_tag: true
  static_image_support: false
