development:
  adapter: postgresql
  database: hesigram_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hesigram_test
  host: localhost
  pool: 5
  timeout: 5000